FROM node:16.18.1

# for node-canvas
RUN apt update && apt install -y build-essential libcairo2-dev libpango1.0-dev \
  libjpeg-dev libgif-dev librsvg2-dev

WORKDIR /home/node/workspace
USER node

COPY ./ .
COPY ./devtools/tasks/getMastercodeVersionFolderName-overwrite.js ./devtools/tasks/getMastercodeVersionFolderName.js

RUN npm install
RUN npm install http-server
RUN npm run buildPortal

CMD [ "npx", "http-server", "./dist" ]
