FROM node:16.18.1

# for node-canvas
RUN apt update && apt install -y build-essential libcairo2-dev libpango1.0-dev \
  libjpeg-dev libgif-dev librsvg2-dev

WORKDIR /home/node/workspace

COPY ./frontend .
COPY ./frontend/devtools/tasks/getMastercodeVersionFolderName-overwrite.js ./devtools/tasks/getMastercodeVersionFolderName.js

RUN npm install -g husky
RUN npm install
RUN npm run buildPortal

RUN npm install --global http-server
CMD [ "http-server", "./dist" ]