version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  api:
    build: api/.
    env_file:
      - ./api/configs/dev_environment
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - geoserver
      - nginx

  frontend:
    build: frontend/.
    depends_on:
      - nginx
    working_dir: /home/node/workspace
    user: node
    command: "npm start"
    volumes:
      - ./frontend:/home/node/workspace

  geoserver:
    image: kartoza/geoserver:2.22.0
    depends_on:
      - postgis
    volumes:
      - ./api/data/geoserver:/opt/geoserver/data_dir
    env_file:
      - ./geoserver/configs/geoserver
    platform:
      "linux/amd64"

  postgis:
    image: postgis/postgis:14-3.3
    volumes:
      - ./api/initializers/db:/docker-entrypoint-initdb.d:delegated
      - ./geoserver/data/pg_data:/var/lib/postgresql/data
    env_file:
      - ./geoserver/configs/postgis
    platform:
      "linux/amd64"
