version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  api:
    build: ./api
    command: "bash ./scripts/entrypoint.sh"
    env_file:
      - ./api/configs/prod_environment
    volumes:
      - ./api:/home/python/workspace
      - ./api/data:/home/python/.local
    depends_on:
      - geoserver
      - nginx

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    working_dir: /home/node/workspace
    user: node
    ports:
      - "9001:8080"

  geoserver:
    image: kartoza/geoserver:2.22.0
    depends_on:
      - postgis
    volumes:
      - ./geoserver/data/geoserver:/opt/geoserver/data_dir
    env_file:
      - ./geoserver/configs/geoserver

  postgis:
    image: postgis/postgis:14-3.3
    volumes:
      - ./api/initializers/db:/docker-entrypoint-initdb.d:delegated
      - ./geoserver/data/pg_data:/var/lib/postgresql/data
    env_file:
      - ./geoserver/configs/postgis
